[package]
name = "ring0-gui"
version.workspace = true
edition.workspace = true

build = "build.rs"

[dependencies]
cxx-qt = "0.9"
cxx-qt-lib = "0.9"
cxx = "1"
ring0-common = { path = "../ring0-common" }
tokio = { version = "1", features = ["full"] }
capnp = "0.26"
anyhow = "1"
zbus = "5"
serde_json = "1"

[build-dependencies]
cxx-qt-build = "0.9"
